# From SQL to Pandas Challenge 4

In [1]:
# import libraries
import pandas as pd

# load data
# This code is made to load our data stored on Google Drive
def gd_path(file_id):
    """Generate a shareable link from Google Drive file id."""
    return f"https://drive.google.com/uc?export=download&id={file_id}"

# Google Drive file ids
files_id = {
    "titles": "1PLdn50N9GRa53ZbuVWo0l47F_IXdvlEm",
    "sales": "1fzFc9rwYmVIPaGOFmhLVxCi3kg19vNU2",
    "publishers": "1s9E8_AVOziTrowb3wyh2jg3PV763VOyq",
    "employee": "1h9mUjsVqpP74b1w0x7KOw37n_n9Ulkt5",
    "authors": "1fEF89Nhe61EebAljKlwFwfEuokK0o6aJ"
}

# Read data from Google Drive
sales = pd.read_csv(gd_path(files_id["sales"]), sep=";")
authors = pd.read_csv(gd_path(files_id["authors"]), sep=";")
publishers = pd.read_csv(gd_path(files_id["publishers"]), sep=";")
titles = pd.read_csv(gd_path(files_id["titles"]), sep=";")
employee = pd.read_csv(gd_path(files_id["employee"]), sep=";")

## 1.&nbsp;From how many different states are our authors?

In [6]:
authors['state'].unique().size

8

### Hint:

In SQL the syntax is:

```sql
SELECT COUNT(DISTINCT state)
FROM authors;
```

## 2.&nbsp;How many publishers are based in the USA?

In [11]:
(publishers['country'] == 'USA').sum()

6

### Hint:

In SQL the syntax is:

```sql
SELECT  COUNT(pub_id)
FROM publishers
WHERE country ="USA" ;
```

## 3.&nbsp;What's the average quantity of titles sold per sale by store 7131?

In [17]:
sales.loc[sales['stor_id'] == 7131, 'qty'].mean()

21.666666666666668

### Hint:

In SQL the syntax is:

```sql
SELECT AVG(qty)
FROM sales
WHERE stor_id=7131;
```

## 4.&nbsp;When was the employee with the highest level hired?

In [19]:
employee.sort_values(by = 'job_lvl').tail(1)['hire_date']

26    1989-03-01 00:00:00
Name: hire_date, dtype: object

### Hint:

In SQL the syntax is:

```sql
SELECT hire_date
FROM employee
ORDER BY job_lvl DESC
LIMIT 1;
```

## 5.&nbsp;What's the average price of psychology books?

In [21]:
titles[titles['type'] == 'psychology']['price'].mean()

13.504

### Hint:

In SQL the syntax is:

```sql
SELECT AVG(price)
FROM titles
WHERE type = "psychology";
```

## 6.&nbsp;Which category of books has had more year-to-date sales, "business" or "popular_comp"? You can write two queries to answer this question.

### business

In [26]:
'business' if titles.loc[titles['type'] == 'business', 'ytd_sales'].sum() > titles.loc[titles['type'] == 'popular_comp', 'ytd_sales'].sum() else 'popular_comp'

'business'

### Hint:

In SQL the syntax is:

```sql
SELECT SUM(ytd_sales), type
FROM titles
WHERE type = "business";
```

### popular_comp

### Hint:

In SQL the syntax is:

```sql
SELECT SUM(ytd_sales), type
FROM titles
WHERE type = "popular_comp";
```

## 7.&nbsp;What's the title and the price of the most expensive book?

In [31]:
titles[['title', 'price']].sort_values(by = 'price').tail(1)

                      title  price
7  But Is It User Friendly?  22.95

### Hint:

In SQL the syntax is:

```sql
SELECT title, price
FROM titles
ORDER BY price DESC
LIMIT 1;
```

## 8.&nbsp;What's the price of the most expensive psychology book?

In [36]:
titles.loc[titles['type'] == 'psychology', 'price'].sort_values().tail(1)

10    21.59
Name: price, dtype: float64

### Hint:

In SQL the syntax is:

```sql
SELECT MAX(price)
FROM titles
WHERE type = "psychology";
```

## 9.&nbsp;How many authors live in either San Jose or Salt Lake City?

In [42]:
authors['city'].isin(['San Jose', 'Salt Lake City']).sum()

3

### Hint:

In SQL the syntax is:

```sql
SELECT COUNT(au_id)
FROM authors
WHERE (city = "San Jose"
OR city = "Salt Lake City");
```